language: node_js
node_js:
  - '12'
dist: trusty
env:
  - DOCKER_COMPOSE_VERSION=1.4.2 CI=true
services:
  - docker
before_install:
  - docker build -t benhalverson/docker-kubernates-prod -f Dockerfile.dev .
cache: 
    - node_modules
script:
  - docker run -e CI=true benhalverson/docker-kubernates-prod npm run test