language: node_js
node_js:
  - '12'
dist: bionic
services:
  - docker
before_install:
  - docker build -t benhalverson/docker-kubernates-prod -f Dockerfile.dev .
cache: 
    - node_modules
script:
  - docker run -e CI=true benhalverson/docker-kubernates-prod npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-demo"
  env: "DockerDemo-env"
  bucket_name: "elasticbeanstalk-us-west-2-811145310164"
  bucket_path: "docker-demo"
  on:
    branch: master