sudo: required
services:
  - docker

before_install:
  - docker build -t benhalverson/docker-kubernates-prod -f Dockerfile.dev .

script:
  - docker run -e CI=true benhalverson/docker-kubernates-prod npm run test -- --coverage
  