language: node_js
node_js:
  - '12'
dist: bionic
services:
  - docker
before_install:
  - docker build -t benhalverson/docker-kubernates-prod -f Dockerfile.dev .
cache: 
    - node_modules
script:
  - docker run -e CI=true benhalverson/docker-kubernates-prod npm run test